//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopUI.SliceOfPieReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SliceOfPieReference.IClientSystemFacade2")]
    public interface IClientSystemFacade2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientSystemFacade2/ShareDocuments", ReplyAction="http://tempuri.org/IClientSystemFacade2/ShareDocumentsResponse")]
        void ShareDocuments(string username, string password, string[] users, string[] documents, string permission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientSystemFacade2/ShareFolder", ReplyAction="http://tempuri.org/IClientSystemFacade2/ShareFolderResponse")]
        void ShareFolder(string username, string password, string[] users, string folder, string permission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientSystemFacade2/GetInvitations", ReplyAction="http://tempuri.org/IClientSystemFacade2/GetInvitationsResponse")]
        string[] GetInvitations(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientSystemFacade2/AcceptInvitations", ReplyAction="http://tempuri.org/IClientSystemFacade2/AcceptInvitationsResponse")]
        void AcceptInvitations(string username, string password, string[] accepts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientSystemFacade2/Synchronize", ReplyAction="http://tempuri.org/IClientSystemFacade2/SynchronizeResponse")]
        string[][] Synchronize(string username, string password, string[][] files);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientSystemFacade2Channel : DesktopUI.SliceOfPieReference.IClientSystemFacade2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientSystemFacade2Client : System.ServiceModel.ClientBase<DesktopUI.SliceOfPieReference.IClientSystemFacade2>, DesktopUI.SliceOfPieReference.IClientSystemFacade2 {
        
        public ClientSystemFacade2Client() {
        }
        
        public ClientSystemFacade2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientSystemFacade2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientSystemFacade2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientSystemFacade2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ShareDocuments(string username, string password, string[] users, string[] documents, string permission) {
            base.Channel.ShareDocuments(username, password, users, documents, permission);
        }
        
        public void ShareFolder(string username, string password, string[] users, string folder, string permission) {
            base.Channel.ShareFolder(username, password, users, folder, permission);
        }
        
        public string[] GetInvitations(string username, string password) {
            return base.Channel.GetInvitations(username, password);
        }
        
        public void AcceptInvitations(string username, string password, string[] accepts) {
            base.Channel.AcceptInvitations(username, password, accepts);
        }
        
        public string[][] Synchronize(string username, string password, string[][] files) {
            return base.Channel.Synchronize(username, password, files);
        }
    }
}
